-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.newsletter
(
    id serial NOT NULL,
    title character varying(100) COLLATE pg_catalog."default" NOT NULL,
    teaser_text character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    pdf_file_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    thumbnail_file_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    published date NOT NULL,
    CONSTRAINT newsletter_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.subscriber
(
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    creation_date date NOT NULL,
    CONSTRAINT subscriber_pkey PRIMARY KEY (email)
);

CREATE TABLE IF NOT EXISTS public.users
(
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (email)
);
END;